-- SUPABASE SETUP: jalankan di SQL Editor project Supabase.
create table if not exists public.wedding_guests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  attendance text not null check (attendance in ('Hadir','Tidak hadir')),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.wedding_guests enable row level security;

drop policy if exists "Public can read wedding guests" on public.wedding_guests;
create policy "Public can read wedding guests"
on public.wedding_guests for select
to anon, authenticated
using (true);

drop policy if exists "Public can submit wedding guests" on public.wedding_guests;
create policy "Public can submit wedding guests"
on public.wedding_guests for insert
to anon, authenticated
with check (true);

-- Aktifkan Realtime agar daftar ucapan dapat diperbarui tanpa refresh.
alter publication supabase_realtime add table public.wedding_guests;
