-- SUPABASE SCHEMA — RSVP, WISHES, DAN REPLY
-- Jalankan SELURUH SQL ini di Supabase > SQL Editor.
-- Aman digunakan untuk instalasi baru maupun memperbarui schema versi sebelumnya.

create table if not exists public.wedding_wishes (
  id bigint generated by default as identity primary key,
  name text not null,
  attendance text,
  message text not null,
  parent_id bigint,
  created_at timestamptz not null default now()
);

-- Migrasi jika sebelumnya sudah memakai schema lama.
alter table public.wedding_wishes add column if not exists parent_id bigint;
alter table public.wedding_wishes alter column attendance drop not null;

-- Hapus constraint lama bila ada, lalu pasang validasi yang mendukung balasan.
alter table public.wedding_wishes drop constraint if exists wedding_wishes_attendance_check;
alter table public.wedding_wishes drop constraint if exists wedding_wishes_name_check;
alter table public.wedding_wishes drop constraint if exists wedding_wishes_message_check;
alter table public.wedding_wishes drop constraint if exists wedding_wishes_parent_id_fkey;

alter table public.wedding_wishes
  add constraint wedding_wishes_name_check check (char_length(name) between 1 and 80),
  add constraint wedding_wishes_message_check check (char_length(message) between 1 and 500),
  add constraint wedding_wishes_attendance_check check (
    (parent_id is null and attendance in ('Hadir','Tidak Hadir','Masih Dipertimbangkan'))
    or
    (parent_id is not null and attendance is null)
  ),
  add constraint wedding_wishes_parent_id_fkey foreign key (parent_id)
    references public.wedding_wishes(id) on delete cascade;

create index if not exists wedding_wishes_parent_id_idx on public.wedding_wishes(parent_id);
create index if not exists wedding_wishes_created_at_idx on public.wedding_wishes(created_at desc);

alter table public.wedding_wishes enable row level security;

-- Tamu boleh membaca daftar ucapan dan balasan.
drop policy if exists "public read wedding wishes" on public.wedding_wishes;
create policy "public read wedding wishes"
on public.wedding_wishes
for select
to anon
using (true);

-- Tamu boleh menambahkan RSVP, ucapan, dan balasan.
drop policy if exists "public insert wedding wishes" on public.wedding_wishes;
create policy "public insert wedding wishes"
on public.wedding_wishes
for insert
to anon
with check (true);

-- Tidak ada policy update/delete untuk anon, jadi tamu tidak dapat mengedit/menghapus.
